# Generated by Django 5.0.3 on 2024-12-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_ratings_product_reivews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reivews',
        ),
    ]
