# Generated by Django 5.0.3 on 2024-12-20 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0006_rename_product_review_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=400)),
                ('zip_code', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=400)),
                ('state', models.CharField(default='', max_length=400)),
                ('country', models.CharField(default='', max_length=400)),
                ('phone_number', models.CharField(default='', max_length=400)),
                ('total_amount', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[(' Paid', 'Paid'), (' Unpaid', 'Unpaid')], default=' Unpaid', max_length=40)),
                ('payment_mode', models.CharField(choices=[(' Cod', 'Cod'), (' Card', 'Card')], default=' Cod', max_length=40)),
                ('status', models.CharField(choices=[(' Processing', 'Processing'), (' Shipped', 'Shipped'), (' Deliverd', 'Deliverd')], default=' Processing', max_length=60)),
                ('createAt', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
